version: '3.1'
services:
  testing:
    build:
      context: .
    environment:
      SERVER: http://envhub:8080
      K3D: ${K3D}
    depends_on:
      envhub:
        condition: service_started
    links:
      - envhub
  envhub:
    image: ghcr.io/linuxsuren/environment-hub:master
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.21
    healthcheck:
      test: ["CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/8080"]
      interval: 3s
      timeout: 60s
      retries: 10
      start_period: 3s
