version: '3.1'
services:
  testing:
    build:
      context: .
    environment:
      SERVER: http://server:8080
    depends_on:
      server:
        condition: service_started
    links:
      - server
  server:
    image: ghcr.io/linuxsuren/environment-hub:master
    environment:
      - ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH=go1.21
    healthcheck:
      test: ["CMD", "bash", "-c", "cat < /dev/null > /dev/tcp/127.0.0.1/8080"]
      interval: 3s
      timeout: 60s
      retries: 10
      start_period: 3s
